### ISSUE TITLE
ACMClient.list()出错：[list] exception the JSON object must be str, not 'bytes' occur

### ISSUE THREAD

**Issue by tornadocs** [alibaba/acm-sdk-python#1]
467 resp = self._do_sync_req("/diamond-server/basestone.do", None, params, None, self.default_timeout)
468 d = resp.read()
469 return json.loads(d)

需改为return json.loads(d.decode("utf-8")) 。

**Comment by zhouwenb** [comment]
请问使用的python版本？

**Comment by tornadocs** [comment]
Ubuntu 16.04.4 LTS,Python 3.5.2

**Comment by zhouwenb** [comment]
确认3.5.2版本存在此问题，0.3.13版本已修复，可以升级到此版本解决。
